query GetQuizzes {
  quizzes(pagination: { limit: 50 }) {
    name
    time_limit
    exam_date
    documentId
    create_by {
      fullname
    }
    questions {
      quest_text
    }
  }
}

query GetQuizz($documentId: ID!) {
  quizz(documentId: $documentId) {
    name
    time_limit
    exam_date
    create_by {
      fullname
    }
    questions {
      documentId
      quest_text
      answers {
        answer_text
        documentId
      }
    }
  }
}

mutation CreateQuizz($data: QuizzInput!) {
  createQuizz(data: $data) {
    name
    number_ques
    time_limit
    start_time
    end_time
    exam_date
    class
    documentId
  }
}

mutation UpdateQuizz($documentId: ID!, $data: QuizzInput!) {
  updateQuizz(documentId: $documentId, data: $data) {
    documentId
    name
    class
    exam_date
  }
}

mutation DeleteQuizz($documentId: ID!) {
  deleteQuizz(documentId: $documentId) {
    documentId
  }
}
