query GetUserQuizz($userId: ID!) {
  usersPermissionsUser(documentId: $userId) {
    user_quizzes(
      filters: { publishedAt: { notNull: true } }
      pagination: { limit: 50 }
    ) {
      quiz {
        questions {
          quest_text
        }
        documentId
        name
      }
      start_at
      completed_at
      score
    }
  }
}

mutation CreateUserQuizz($data: UserQuizzInput!) {
  createUserQuizz(data: $data) {
    documentId
    score
    start_at
    completed_at
    status_user_quiz
    quiz {
      name
      documentId
    }
    result
    user {
      fullname
    }
  }
}

mutation SubmitUserQuizz($documentId: ID!, $data: UserQuizzInput!) {
  updateUserQuizz(documentId: $documentId, data: $data) {
    score
    start_at
    completed_at
    status_user_quiz
    quiz {
      name
      documentId
    }
    result
    user {
      fullname
    }
  }
}

query GetListUserQuizz($documentId: ID!) {
  quizz(documentId: $documentId) {
    user_quizzes {
      user {
        fullname
        username
      }
      score
      createdAt
      status_user_quiz
    }
  }
}
